// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package repository

import (
	"context"
)

const approveComment = `-- name: ApproveComment :one
UPDATE comments
SET status = 'approved'
WHERE id = $1
RETURNING id, post_id, author_name, content, status, created_at
`

func (q *Queries) ApproveComment(ctx context.Context, id int32) (Comment, error) {
	row := q.db.QueryRow(ctx, approveComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorName,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, author_name, content, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, post_id, author_name, content, status, created_at
`

type CreateCommentParams struct {
	PostID     int32  `json:"post_id"`
	AuthorName string `json:"author_name"`
	Content    string `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.PostID, arg.AuthorName, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorName,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const listAllCommentsByPostID = `-- name: ListAllCommentsByPostID :many
SELECT id, post_id, author_name, content, status, created_at
FROM comments
WHERE post_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAllCommentsByPostID(ctx context.Context, postID int32) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listAllCommentsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorName,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedCommentsByPostID = `-- name: ListApprovedCommentsByPostID :many
SELECT id, post_id, author_name, content, status, created_at
FROM comments
WHERE post_id = $1 AND status = 'approved'
ORDER BY created_at ASC
`

func (q *Queries) ListApprovedCommentsByPostID(ctx context.Context, postID int32) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listApprovedCommentsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorName,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
