// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID         int32              `json:"id"`
	PostID     int32              `json:"post_id"`
	AuthorName string             `json:"author_name"`
	Content    string             `json:"content"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Post struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Content       string             `json:"content"`
	Excerpt       pgtype.Text        `json:"excerpt"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	Status        string             `json:"status"`
	AuthorID      int32              `json:"author_id"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PostTag struct {
	PostID int32 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

type Tag struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type User struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
