// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, slug, content, excerpt, cover_image_url, status, author_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, title, slug, content, excerpt, cover_image_url, status, author_id, published_at, created_at, updated_at
`

type CreatePostParams struct {
	Title         string      `json:"title"`
	Slug          string      `json:"slug"`
	Content       string      `json:"content"`
	Excerpt       pgtype.Text `json:"excerpt"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
	Status        string      `json:"status"`
	AuthorID      int32       `json:"author_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.Title,
		arg.Slug,
		arg.Content,
		arg.Excerpt,
		arg.CoverImageUrl,
		arg.Status,
		arg.AuthorID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImageUrl,
		&i.Status,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts
WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT
    p.id, p.title, p.slug, p.content, p.excerpt, p.cover_image_url,
    p.status, p.author_id, p.published_at, p.created_at, p.updated_at,
    u.name AS author_name
FROM posts p
INNER JOIN users u ON u.id = p.author_id
WHERE p.id = $1
`

type GetPostByIDRow struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Content       string             `json:"content"`
	Excerpt       pgtype.Text        `json:"excerpt"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	Status        string             `json:"status"`
	AuthorID      int32              `json:"author_id"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	AuthorName    string             `json:"author_name"`
}

func (q *Queries) GetPostByID(ctx context.Context, id int32) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImageUrl,
		&i.Status,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
	)
	return i, err
}

const getPostBySlug = `-- name: GetPostBySlug :one
SELECT
    p.id, p.title, p.slug, p.content, p.excerpt, p.cover_image_url,
    p.status, p.author_id, p.published_at, p.created_at, p.updated_at,
    u.name AS author_name
FROM posts p
INNER JOIN users u ON u.id = p.author_id
WHERE p.slug = $1
`

type GetPostBySlugRow struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Content       string             `json:"content"`
	Excerpt       pgtype.Text        `json:"excerpt"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	Status        string             `json:"status"`
	AuthorID      int32              `json:"author_id"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	AuthorName    string             `json:"author_name"`
}

func (q *Queries) GetPostBySlug(ctx context.Context, slug string) (GetPostBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPostBySlug, slug)
	var i GetPostBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImageUrl,
		&i.Status,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
	)
	return i, err
}

const listAllPosts = `-- name: ListAllPosts :many
SELECT id, title, slug, excerpt, cover_image_url, status, author_id, published_at, created_at, updated_at
FROM posts
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllPostsRow struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Excerpt       pgtype.Text        `json:"excerpt"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	Status        string             `json:"status"`
	AuthorID      int32              `json:"author_id"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllPosts(ctx context.Context, arg ListAllPostsParams) ([]ListAllPostsRow, error) {
	rows, err := q.db.Query(ctx, listAllPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPostsRow
	for rows.Next() {
		var i ListAllPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.CoverImageUrl,
			&i.Status,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPosts = `-- name: ListPublishedPosts :many
SELECT id, title, slug, excerpt, cover_image_url, status, author_id, published_at, created_at, updated_at
FROM posts
WHERE status = 'published'
ORDER BY published_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPublishedPostsRow struct {
	ID            int32              `json:"id"`
	Title         string             `json:"title"`
	Slug          string             `json:"slug"`
	Excerpt       pgtype.Text        `json:"excerpt"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	Status        string             `json:"status"`
	AuthorID      int32              `json:"author_id"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedPostsRow
	for rows.Next() {
		var i ListPublishedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.CoverImageUrl,
			&i.Status,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPost = `-- name: PublishPost :one
UPDATE posts
SET status = 'published',
    published_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, title, slug, content, excerpt, cover_image_url, status, author_id, published_at, created_at, updated_at
`

func (q *Queries) PublishPost(ctx context.Context, id int32) (Post, error) {
	row := q.db.QueryRow(ctx, publishPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImageUrl,
		&i.Status,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title = $2,
    content = $3,
    excerpt = $4,
    cover_image_url = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, title, slug, content, excerpt, cover_image_url, status, author_id, published_at, created_at, updated_at
`

type UpdatePostParams struct {
	ID            int32       `json:"id"`
	Title         string      `json:"title"`
	Content       string      `json:"content"`
	Excerpt       pgtype.Text `json:"excerpt"`
	CoverImageUrl pgtype.Text `json:"cover_image_url"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Excerpt,
		arg.CoverImageUrl,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Content,
		&i.Excerpt,
		&i.CoverImageUrl,
		&i.Status,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
