// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	AddTagToPost(ctx context.Context, arg AddTagToPostParams) error
	ApproveComment(ctx context.Context, id int32) (Comment, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteComment(ctx context.Context, id int32) error
	DeletePost(ctx context.Context, id int32) error
	DeleteTag(ctx context.Context, id int32) error
	GetPostByID(ctx context.Context, id int32) (GetPostByIDRow, error)
	GetPostBySlug(ctx context.Context, slug string) (GetPostBySlugRow, error)
	GetTagBySlug(ctx context.Context, slug string) (Tag, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	ListAllCommentsByPostID(ctx context.Context, postID int32) ([]Comment, error)
	ListAllPosts(ctx context.Context, arg ListAllPostsParams) ([]ListAllPostsRow, error)
	ListAllPostsByAuthor(ctx context.Context, arg ListAllPostsByAuthorParams) ([]ListAllPostsByAuthorRow, error)
	ListApprovedCommentsByPostID(ctx context.Context, postID int32) ([]Comment, error)
	ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsByPostID(ctx context.Context, postID int32) ([]Tag, error)
	ListTagsByPostIDs(ctx context.Context, dollar_1 []int32) ([]ListTagsByPostIDsRow, error)
	PublishPost(ctx context.Context, id int32) (Post, error)
	RemoveTagFromPost(ctx context.Context, arg RemoveTagFromPostParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
