// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package repository

import (
	"context"
)

const addTagToPost = `-- name: AddTagToPost :exec
INSERT INTO post_tags (post_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToPostParams struct {
	PostID int32 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

func (q *Queries) AddTagToPost(ctx context.Context, arg AddTagToPostParams) error {
	_, err := q.db.Exec(ctx, addTagToPost, arg.PostID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug
`

type CreateTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, slug
FROM tags
WHERE slug = $1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Slug)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug
FROM tags
ORDER BY name ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByPostID = `-- name: ListTagsByPostID :many
SELECT t.id, t.name, t.slug
FROM tags t
INNER JOIN post_tags pt ON pt.tag_id = t.id
WHERE pt.post_id = $1
`

func (q *Queries) ListTagsByPostID(ctx context.Context, postID int32) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByPostIDs = `-- name: ListTagsByPostIDs :many
SELECT pt.post_id, t.id, t.name, t.slug
FROM tags t
INNER JOIN post_tags pt ON pt.tag_id = t.id
WHERE pt.post_id = ANY($1::int[])
`

type ListTagsByPostIDsRow struct {
	PostID int32  `json:"post_id"`
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Slug   string `json:"slug"`
}

func (q *Queries) ListTagsByPostIDs(ctx context.Context, dollar_1 []int32) ([]ListTagsByPostIDsRow, error) {
	rows, err := q.db.Query(ctx, listTagsByPostIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsByPostIDsRow
	for rows.Next() {
		var i ListTagsByPostIDsRow
		if err := rows.Scan(
			&i.PostID,
			&i.ID,
			&i.Name,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromPost = `-- name: RemoveTagFromPost :exec
DELETE FROM post_tags
WHERE post_id = $1 AND tag_id = $2
`

type RemoveTagFromPostParams struct {
	PostID int32 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromPost(ctx context.Context, arg RemoveTagFromPostParams) error {
	_, err := q.db.Exec(ctx, removeTagFromPost, arg.PostID, arg.TagID)
	return err
}
